os: linux
dist: xenial
language: python
python: '3.6'
addons:
  snaps:
  - name: snapcraft
    classic: true
  - name: lxd
install: make install-dependencies
before_script: make lint
script: make build
deploy:
  provider: releases
  token:
    secure: Bs6gURQUH0uPGKLzY3juTYPcDL+Y8lNEFqXvMlKc5YibVY0wqq0I5KANPXosilfvnZZ4kjjj/IPBkFPhC7ZBqBXIxoLWc66R2jWH67C2M4qeM67a6fRIF6rj264+ZTdTEDYwemOO9l7maRjl0Yyy2nRoswjYyj5jch0C1DD3qY9v+3b/8/h9BuLQLihEbPNKTmsvPhvaf8ioLNtKyG3QlFK4AtYRiKdLc6r1i/r1PT2maaq9XlXDEkAeI8OVdzZ05URZuIOJWLCL1UTVk+2210815K/nxjyVUldzV5MD6EL+HvR7IXcXzuNRIPl2/YEh3zJO0EQ8zJf47/lPh1CF2sYmzpKlLP+RvZXKN6SUwpxXsf7NFie6FPSUKBC+nqmAm6acGHVWNVVMaS3P9uPVJn7OXA6aldgkR0KLsyx1g3Ci25YizSO0FnoD3SdPVXanGkcauQOrc/AJWAEUir/POVhVW/OAlpR4G7NLw2CEu4k4kBntTLqqGsgOYPOSVuSPW0ljx9C0MGnSW1/zcNHZ/1duE5jEIHBoDG6e5VGW07yGqf1PqR7r2IOGNIHdosoBOjRysaG0hw3GxxZ6do6+idw1AlFqqKilAFD3U4yrzFbCPBllt+Tvp2go8zg7w13z/TWmk7gLvsfm/MRrQvNhfuom4muoGLLM4fGD6gyt0W8=
  file: slurm_*_amd64.snap
  on:
    repo: omnivector-solutions/snap-slurm
    tags: 'true'
notifications:
  slack:
    rooms:
      secure: EfVvPqUeF82toDMiJ0aLjdd6VyaBIij5dCkMie9HHc7VjzgLDtj5SwU8HvnyMUfAIUYzK0pm8cJCfayDBzBtbwa+HUBpE5fCDYT1x5MyOECdg6yW4rmzJm6mCb7qdudpdCwvoEdU8rsGtbRBCkmNaNDh0a95P6Ste6xLzVvH9w/GbMhrdsF92zKJWk74h3zazo8knbDt+tF+S3SMRiZbF+AEQ9yAQx/foICp4YLfy19nFyw0sk2pGWxQLMwtqyJLPhZqJaqyb3BSeg7ls7PbWCoExZ5KPs8K6I+B/YLl2yYp+3Vqen5gEN2PvV/OJI5mGR1cp4MZOlQ1vJSzs7RHGtb9pbYCK2xiBa4fq+A4+1xTwe3k4MwZLLpV6D7/HGYouFj4RTFoQDEH8fTG9eKy4ZkCt8YxGAiKtkJIggCBvEXLMJmxE2dDXAQbq5GoL8ENWJnoewo5ea6pw2n6VOtA6C+H7GGVqho+eiZGtOh7EVU0BNmbwQ4BkptgT8nMwoz2Zt8o5Ra5DXcbqG0p7E9e3N6p1/bQF/qOHVFuz815YbYdVhAk/dawjKQTGQeaWzy2Lsj9TgcFbfUQnLf52zf5c9XqPUaB5kh5GTtqDERhwVvfh0ytNT+B7QFHhn76qJJkuZF/7TEiWBRAnV7KLgUeR4g7weBCSMSMZ/rqsvtNB7M=
    on_success: always
