# if: branch = master
os: linux
dist: bionic
language: python
python: 3.6
addons:
  snaps:
  - name: snapcraft
    classic: true
install: make install-dependencies
script:
  - make lint
  - make test
  - make build
  - make install
  - make mode-all
  - make snap-debug
