version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          command: flake8 src/hooks/bin/configure
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: make install-snapcraft-dependencies
      - run:
          name: "Build Snap"
          command: make build
workflows:
  version: 2.1
  craft_snap:
    jobs:
      - lint
      # - build