version: 2.1
workflows:
  lint:
    jobs:
      - flake8
  build-and-test:
    jobs:
      - snapcraft:
          filters:
            branches:
              only: staging # End-to-end tests only on staging branches
  release:
    jobs:
      - snapcraft:
          filters:
            branches:
              only: circleci-releases #/20\..*/  # Deploy only on versioned branches
      - release_snapstore:
          requires:
            - snapcraft
      - release_github:
          requires:
            - snapcraft
jobs:
  flake8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          name: Run flake8
          command: |
            flake8 src/hooks/bin/configure
            flake8 src/slurm-bins/bin/slurm-version
  snapcraft:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
              sudo apt-get update
              sudo apt-get install --only-upgrade -y snapd
              sudo apt-get purge lxd lxd-client lxcfs
              sudo snap install lxd
              sudo lxd init --auto
              sudo snap install snapcraft --classic
      - run:
          name: "Build Snap"
          command: /snap/bin/snapcraft --use-lxd
      - save_cache:
          name: Store Slurm Snap for next workflow
          key: SlurmSnap-${CIRCLE_SHA1}
          paths:
            - slurm_20.02.1_amd64.snap
  release_snapstore:
    machine:
      image: ubuntu-1604:202004-01 # Snapcraft images currently broken with python3 errors
    steps:
      - run:
          name: "Install Dependencies"
          command: |
              sudo apt-get update
              sudo apt-get install --only-upgrade -y snapd
              sudo snap install snapcraft --classic
              sudo snap install review-tools
      - restore_cache:
          name: Restore Slurm Snap for deployment
          key: SlurmSnap-${CIRCLE_SHA1}
      - run:
          name: "Review Snap"
          command: /snap/bin/review-tools.snap-review slurm_20.02.1_amd64.snap
      - run:
          name: "Publish to Store"
          command: |
            mkdir .snapcraft
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            /snap/bin/snapcraft upload slurm_20.02.1_amd64.snap --release candidate
  release_github:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - restore_cache:
          name: Restore Slurm Snap for deployment
          key: SlurmSnap-${CIRCLE_SHA1}
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB} -n '20.02.1 Strict-Mode' -c ${CIRCLE_SHA1} -replace -recreate 20.02.1-strict slurm_20.02.1_amd64.snap
