version: 2.1
workflows:
  build_and_test:
    jobs:
      - flake8
      # - shellcheck:
      #     requires:
      #       - flake8
      # - snapcraft:
      #     requires:
      #       - flake8
      # - terraform_and_test:
      #     requires:
      #       - snapcraft
      # - release_snapstore:
      #     requires:
      #       - flake8
      - release_github:
          requires:
            - flake8
jobs:
  flake8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          name: Run flake8
          command: |
            flake8 src/hooks/bin/configure
            flake8 src/slurm-bins/bin/slurm-version
      - save_cache:
          name: Store the Snap for the next workflow
          key: Makefile
          paths:
            - ~/project/Makefile
  shellcheck:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - restore_cache:
          name: Restore Slurm-Snap
          key: Makefile
      - run:
          name: Install Shellcheck
          command: |
            sudo apt-get update
            sudo apt-get install -y shellcheck
      - run:
          name: Run Spellcheck
          command: shellcheck src/hooks/bin/install
  snapcraft:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
              sudo apt-get update
              sudo apt-get install --only-upgrade -y snapd
              sudo apt-get purge lxd lxd-client lxcfs
              sudo snap install lxd
              sudo lxd init --auto
              sudo snap install snapcraft --classic
      - run:
          name: "Build Snap"
          command: time sudo snapcraft --use-lxd
      - save_cache:
          name: Store Slurm Snap for next workflow
          key: SlurmSnap
          paths:
            - slurm_20.02.1_amd64.snap
  terraform_and_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - restore_cache:
          name: Restore Slurm Snap for deployment
          key: SlurmSnap
      - run:
          name: Move slurm-snap
          command: mv slurm_20.02.1_amd64.snap tf/slurm_20.02.1_amd64.snap
      - run:
          name: Setup SSH key
          command: |
            mkdir -p ~/.ssh
            echo $KEY | base64 --decode > /tmp/id_rsa
            chmod 600 /tmp/id_rsa
      - run:
          name: Install Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
            unzip terraform_0.12.26_linux_amd64.zip
      - run:
          name: Test Terraform
          command: |
            cd tf
            ../terraform init
            ../terraform apply -auto-approve -var "api_key=${VULTR_API_KEY}"
      - run:
          name: Destroy Terraform
          command: |
            cd tf
            ../terraform destroy -auto-approve -var "api_key=${VULTR_API_KEY}"
  release_snapstore:
    docker:
      - image: snapcore/snapcraft:beta
    steps:
      # - restore_cache:
      #     name: Restore Slurm Snap for deployment
      #     key: SlurmSnap
      - run:
          name: "Publish to Store"
          command: |
            mkdir .snapcraft
            echo $SNAP | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            snapcraft push slurm_20.02.1_amd64.snap --release beta
  release_github:
    docker:
      - image: cimg/go:1.13
    steps:
      # - restore_cache:
      #     name: Restore Slurm Snap for deployment
      #     key: SlurmSnap
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB} -recreate 20.02.1 ./Makefile