version: 2.1
workflows:
  lint:
    jobs:
      - flake8
  build-test-release:
    jobs:
      - snapcraft:
          filters:
            branches:
              only: strict-mode
      # - test_ubuntu1804:
      #     requires:
      #       - snapcraft
      - test_ubuntu2004:
          requires:
            - snapcraft
      # - release_github:
      #     requires:
      #       - test_ubuntu2004
      - release_snapstore:
          requires:
            - test_ubuntu2004
jobs:
  flake8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          name: Run flake8
          command: |
            flake8 --ignore=E501 src/hooks/bin/configure
            flake8 src/slurm-bins/bin/slurm-version
  snapcraft:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
              sudo apt-get update
              sudo apt-get install --only-upgrade -y snapd
              sudo apt-get purge lxd lxd-client lxcfs
              sudo snap install lxd
              sudo lxd init --auto
              sudo snap install snapcraft --classic
      - run:
          name: "Build Snap"
          command: echo test
      #       /snap/bin/snapcraft --use-lxd
      #       mv /home/circleci/project/slurm_20.02.1_amd64.snap /home/circleci/project/slurm.snap
      # - save_cache:
      #     name: Store Slurm Snap for next workflow
      #     key: SlurmSnap-{{ .Environment.CIRCLE_SHA1 }}
      #     paths:
      #       - slurm.snap
  test_ubuntu1804:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - restore_cache:
          name: Restore Slurm Snap for deployment
          key: SlurmSnap-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Move slurm-snap
          command: mv /home/circleci/project/slurm.snap /home/circleci/project/tests/ubuntu1804/
      - run:
          name: Setup SSH key
          command: |
            mkdir -p ~/.ssh
            echo $KEY | base64 --decode > /tmp/id_rsa
            chmod 600 /tmp/id_rsa
      - run:
          name: Install Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
            unzip terraform_0.12.26_linux_amd64.zip
      - run:
          name: Test Terraform
          command: |
            cd tests/ubuntu1804
            ../../terraform init
            ../../terraform apply -auto-approve -var "api_key=${VULTR_API_KEY}"
      - run:
          name: Destroy Terraform
          command: |
            cd tests/ubuntu1804
            ../../terraform destroy -auto-approve -var "api_key=${VULTR_API_KEY}"
  test_ubuntu2004:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - restore_cache:
          name: Restore Slurm Snap for deployment
          key: SlurmSnap-59f6081d6df8c4af4395361fe75c283892cf9b66
      - run:
          name: Move slurm-snap
          command: mv /home/circleci/project/slurm.snap /home/circleci/project/tests/ubuntu2004/
      - run:
          name: Setup SSH key
          command: |
            mkdir -p ~/.ssh
            echo $KEY | base64 --decode > /tmp/id_rsa
            chmod 600 /tmp/id_rsa
      - run:
          name: Install Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
            unzip terraform_0.12.26_linux_amd64.zip
      # - run:
      #     name: Test Terraform
      #     command: |
      #       cd tests/ubuntu2004
      #       ../../terraform init
      #       ../../terraform apply -auto-approve -var "api_key=${VULTR_API_KEY}"
      # - run:
      #     name: Destroy Terraform
      #     command: |
      #       cd tests/ubuntu2004
      #       ../../terraform destroy -auto-approve -var "api_key=${VULTR_API_KEY}"
  release_snapstore:
    docker:
      - image: cibuilds/snapcraft:core18
    steps:
      - restore_cache:
          name: Restore Slurm Snap for deployment
          key: SlurmSnap-59f6081d6df8c4af4395361fe75c283892cf9b66  #{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Publish to Store"
          command: |
            mkdir .snapcraft
            echo $SNAP | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            snapcraft push /home/circleci/project/slurm.snap --release edge  
  release_github:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - restore_cache:
          name: Restore Slurm Snap for deployment
          key: SlurmSnap-59f6081d6df8c4af4395361fe75c283892cf9b66
      - run:
          name: "Re-normalize Snap name"
          command: mv /home/circleci/project/slurm.snap /home/circleci/project/slurm_20.02.1_amd64_strict.snap
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB} -n 'Slurm 20.02.1-strict' -c ${CIRCLE_SHA1} -replace -recreate 20.02.1-strict /home/circleci/project/slurm_20.02.1_amd64_strict.snap
