version: 2.1
workflows:
  craft_snap:
    jobs:
      - flake8
      # - shellcheck
      # - snapcraft
      - terraform_and_test
jobs:
  flake8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          name: Run flake8
          command: |
            flake8 src/hooks/bin/configure
            flake8 src/slurm-bins/bin/slurm-version
  shellcheck:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install Shellcheck
          command: |
            sudo apt-get update
            sudo apt-get install -y shellcheck
      - run:
          name: Run Spellcheck
          command: shellcheck src/hooks/bin/install
  snapcraft:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            	sudo apt update
              sudo apt upgrade -y
              sudo snap refresh
              sudo lxd init --auto
              sudo snap install lxd
              sudo lxd.migrate -yes
              sudo snap install snapcraft --classic
              sudo lxd init --auto
      - run:
          name: "Build Snap"
          command: sudo snapcraft --use-
  terraform_and_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget git
            wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
            unzip terraform_0.12.26_linux_amd64.zip
      - run:
          name: Test Git
          command: git clone https://github.com/omnivector-solutions/charm-slurmdbd.git
      - run:
          name: Test Terraform
          command: ./terraform --version
  deliver:
