version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: "Run flake8"
          command: flake8 ./src/hooks/bin/
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: make install-snapcraft-dependencies
      - run:
          name: "Build Snap"
          command: make build
workflows:
  version: 2.1
  lint_and_build:
    jobs:
      - lint
      - build