version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  lint_python:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          name: Run flake8
          command: |
            flake8 src/hooks/bin/configure
            flake8 src/slurm-bins/bin/slurm-version
  lint_bash:
    steps:
      - shellcheck/check

  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: make install-snapcraft-dependencies
      - run:
          name: "Build Snap"
          command: make build
workflows:
  version: 2.1
  craft_snap:
    jobs:
      - lint_python
      - lint_bash
      # - build