version: 2.1
workflows:
  craft_snap:
    jobs:
      - flake8
      # - shellcheck
      - snapcraft
jobs:
  flake8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          name: Run flake8
          command: |
            flake8 src/hooks/bin/configure
            flake8 src/slurm-bins/bin/slurm-version
  shellcheck:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install Shellcheck
          command: |
            sudo apt-get update
            sudo apt-get install -y shellcheck
      - run:
          name: Run Spellcheck
          command: shellcheck src/hooks/bin/install
  snapcraft:
    docker:
      - image: cibuilds/snapcraft:core18
    steps:
      - checkout
      # - run:
      #     name: "Install Dependencies"
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get upgrade -y
      #       sudo apt-get install -y snapd
      #       sudo systemctl enable --now snapd
      #       sudo snap install lxd
      #       sudo snap install snapcraft --classic
      #       sudo lxd init --auto
      - run:
          name: "Build Snap"
          command: snapcraft